export const signOut= async(req, res, next)=>
{
    try{

    }
    catch(err)
    {
        
    }
}