

export const addPharmacy= async(r)=>
{
    try{

    }
    catch(err)
    {
        console.log("The error is", err)
    }
}