const getAllFinishedAppointment= async()=>
{
    try{

    }
    catch(err)
    {
        console.log(err);
        throw
    }
}